### From the box plots we know that following features(x) have impact on independent variable(y) loan_status_altered
    loan_amnt
	funded_amnt
	term
	int_rate
	installment
	emp_length
	annual_inc
	dti
	earliest_cr_line
	revol_util
	total_pymnt
	total_rec_prncp
	total_rec_int
	recoveries
	collection_recovery_fee
	last_pymnt_amnt

In [16]:
import pandas as pd
import numpy as np
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

In [17]:
loan_stat_df_fet_engineered = pd.read_csv('data/loan_stat_df_for_training.csv',low_memory=False, delimiter=',')
loan_stat_train_df = loan_stat_df_fet_engineered
loan_stat_df_fet_engineered.head()

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,purpose,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,open_acc,pub_rec,revol_bal,revol_util,total_acc,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,last_credit_pull_d,acc_now_delinq,delinq_amnt,pub_rec_bankruptcies,tax_liens,debt_settlement_flag,loan_status_altered
0,15000,15000,8725,36,14.27,514,C,C2,9,RENT,60000,Not Verified,201112,Charged Off,debt_consolidation,103xx,NY,15,0,200310,1,7,0,5872,57.6,11,0,0,0,0,0,0,0,201207,0,201902,0,0,0,0,N,Charged Off
1,2500,2500,2500,36,7.51,77,A,A3,10,OWN,12000,Source Verified,201112,Charged Off,debt_consolidation,961xx,CA,16,0,199408,2,13,0,4853,42.2,20,1838,1838,1575,253,0,10,0,201312,77,202103,0,0,0,0,N,Charged Off
2,1000,1000,1000,36,14.65,34,C,C3,10,RENT,18408,Not Verified,201112,Charged Off,major_purchase,080xx,NJ,6,0,199304,2,3,1,2510,83.7,8,91,91,22,12,0,56,10,201201,34,201206,0,0,1,0,N,Charged Off
3,1700,1700,1700,36,7.90,53,A,A4,10,MORTGAGE,37800,Not Verified,201112,Charged Off,home_improvement,805xx,CO,27,0,197907,0,9,0,16333,91.2,27,1221,1221,940,174,0,106,1,201309,53,201610,0,0,0,0,N,Charged Off
4,8575,8575,8575,36,17.58,308,D,D4,10,MORTGAGE,32000,Verified,201112,Charged Off,debt_consolidation,325xx,FL,22,0,200409,1,4,0,20142,89.9,5,4646,4646,2808,1497,0,340,3,201302,308,201610,0,0,0,0,N,Charged Off

In [18]:
loan_stat_train_df["loan_status_altered"] = loan_stat_train_df["loan_status_altered"].map({"Fully Paid": 0, "Charged Off": 1})
loan_stat_train_df.head()

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,purpose,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,open_acc,pub_rec,revol_bal,revol_util,total_acc,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,last_credit_pull_d,acc_now_delinq,delinq_amnt,pub_rec_bankruptcies,tax_liens,debt_settlement_flag,loan_status_altered
0,15000,15000,8725,36,14.27,514,C,C2,9,RENT,60000,Not Verified,201112,Charged Off,debt_consolidation,103xx,NY,15,0,200310,1,7,0,5872,57.6,11,0,0,0,0,0,0,0,201207,0,201902,0,0,0,0,N,1
1,2500,2500,2500,36,7.51,77,A,A3,10,OWN,12000,Source Verified,201112,Charged Off,debt_consolidation,961xx,CA,16,0,199408,2,13,0,4853,42.2,20,1838,1838,1575,253,0,10,0,201312,77,202103,0,0,0,0,N,1
2,1000,1000,1000,36,14.65,34,C,C3,10,RENT,18408,Not Verified,201112,Charged Off,major_purchase,080xx,NJ,6,0,199304,2,3,1,2510,83.7,8,91,91,22,12,0,56,10,201201,34,201206,0,0,1,0,N,1
3,1700,1700,1700,36,7.90,53,A,A4,10,MORTGAGE,37800,Not Verified,201112,Charged Off,home_improvement,805xx,CO,27,0,197907,0,9,0,16333,91.2,27,1221,1221,940,174,0,106,1,201309,53,201610,0,0,0,0,N,1
4,8575,8575,8575,36,17.58,308,D,D4,10,MORTGAGE,32000,Verified,201112,Charged Off,debt_consolidation,325xx,FL,22,0,200409,1,4,0,20142,89.9,5,4646,4646,2808,1497,0,340,3,201302,308,201610,0,0,0,0,N,1

In [19]:
x = np.array(loan_stat_train_df[["loan_amnt","funded_amnt","term","int_rate","installment","emp_length","annual_inc","dti","earliest_cr_line","revol_util","total_pymnt","total_rec_prncp","total_rec_int","recoveries","collection_recovery_fee","last_pymnt_amnt"]])
y = np.array(loan_stat_train_df[["loan_status_altered"]])

In [20]:
y = y.ravel()

In [23]:
from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline

xtrain, xtest, ytrain, ytest = train_test_split(x, y, 
                                                    test_size=0.33, 
                                                    random_state=42)

rf_clf = RandomForestClassifier(criterion='gini', bootstrap=True, random_state=100)
smote_sampler = SMOTE(random_state=9)
pipeline = Pipeline(steps = [['smote', smote_sampler],
                             ['classifier', rf_clf]])
pipeline.fit(xtrain, ytrain)
y_pred = pipeline.predict(xtest)

In [24]:
print(y_pred)

[0 1 0 ... 0 1 0]

In [25]:
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score, accuracy_score, roc_auc_score
print("-------------------------TEST SCORES-----------------------") 
print(f"Recall: { round(recall_score(ytest, y_pred)*100, 4) }")
print(f"Precision: { round(precision_score(ytest, y_pred)*100, 4) }")
print(f"F1-Score: { round(f1_score(ytest, y_pred)*100, 4) }")
print(f"Accuracy score: { round(accuracy_score(ytest, y_pred)*100, 4) }")
print(f"AUC Score: { round(roc_auc_score(ytest, y_pred)*100, 4) }")

-------------------------TEST SCORES-----------------------
Recall: 98.7805
Precision: 100.0
F1-Score: 99.3865
Accuracy score: 99.8072
AUC Score: 99.3902

In [26]:
cm = confusion_matrix(ytest, y_pred)

# Convert confusion matrix to a pandas DataFrame
cm_df = pd.DataFrame(cm, columns=['Predicted 0', 'Predicted 1'], index=['Actual 0', 'Actual 1'])

# Display confusion matrix as a table
print(cm_df)

          Predicted 0  Predicted 1
Actual 0        11793            0
Actual 1           27         2187

AUC score:
A model with a higher AUC score indicates that it is better at distinguishing between the two classes, i.e., it has a higher true positive rate while keeping a lower false positive rate. This means that the model is more accurate in identifying loan defaulters while minimizing the risk of falsely classifying non-defaulters as defaulters.

Accuracy: is calculated as the ratio of the number of correctly classified samples to the total number of samples in the dataset. In other words, it measures how often the model is correct in its predictions of both loan defaulters and non-defaulters.

Precision: is the proportion of positive predictions that are correct, while recall is the proportion of actual positive cases that are correctly identified by the model. In other words, precision measures how well the model predicts loan defaulters among all predicted defaulters, while recall measures how well the model identifies all the actual loan defaulters.

high recall: indicates that the model makes few false negative predictions, meaning that the number of cases where the model failed to identify a loan defaulter but the borrower actually defaulted on the loan is low.

The F1 score: combines both precision and recall into a single metric that represents their harmonic mean. A high F1 score indicates that the model has a good balance between precision and recall, and is able to correctly identify loan defaulters while minimizing false positives and false negatives.